baseurl = "https://example.com"
languageCode = "en-us"
title = "Hugo Grapes Theme"
theme = "hugo-grapes"
enableEmoji = true

[permalinks]
  post = "/news/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "news"
    name = "News Release"
    url = "/news"
    weight = 20

[params]
avatar = "img/grapes.svg"
