backend:
  name: github
  repo: tanearaki/FttTest
  branch: master
 
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
 
collections:
  - name: "news"
    label: "ニュース投稿"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {
          name: "categories",
          label: "Category",
          widget: "select",
          default: "NEWS",
          options: [
              { label: "NEWS", value: "news" },
              { label: "PRESS", value: "press" },
              { label: "INFO", value: "info" }
          ]
        }
      - {label: "Class", name: "class", widget: "select", options: ["news", "press", "info"], required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
