backend:
  name: github
  repo: tanearaki/FttTest
  branch: master
 
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
 
collections:
  - name: "news"
    label: "ニュース投稿"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      #- {label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false}
      #- {label: "Category", name: "categories", widget: "list", options: ["NEWS" ,"PRESS", "INFO"], required: false}
      #- {label: "Class", name: "class", widget: "list", required: false}
      - {label: "Category", name: "postcategories", widget: "select", options: ["NEW" ,"PRESS", "INFO"], default: "NEWS"} 
      - {label: "Class", name: "postclass", widget: "select", options: ["new", "press", "info"], default: "news"}
      #- {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "File", name: "file_upload", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown", options: ["bold", "italic", "code", "link", "heading-one", "heading-two", "quote", "code-block", "bulleted-list"]}
